version: '3.8'

services:
  # Evolution API - WhatsApp Gateway
  evolution-api:
    image: atendai/evolution-api:v2.0.0
    container_name: evolution-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Server Config
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=${EVOLUTION_PUBLIC_URL:-http://localhost:8080}
      
      # Database Config
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://evolution:${POSTGRES_PASSWORD:-evolution123}@postgres-evolution:5432/evolution
      
      # Redis Config  
      - REDIS_ENABLED=true
      - REDIS_URI=redis://redis-evolution:6379/0
      
      # Authentication
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY:-evolution-api-key-2025}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Webhook Config - URL dinámica desde N8N
      - WEBHOOK_GLOBAL_URL=${N8N_WEBHOOK_URL}
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      
      # QR Config
      - QRCODE_LIMIT=10
      - QRCODE_COLOR=#000000
      
      # Instance Config
      - CONFIG_SESSION_PHONE_CLIENT=WhatsApp Business
      - CONFIG_SESSION_PHONE_NAME=SMS_SCANNER_APP
      
      # Logs
      - LOG_LEVEL=info
      - LOG_COLOR=true
    
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    
    depends_on:
      - postgres-evolution
      - redis-evolution
    
    networks:
      - evolution-network

  # PostgreSQL for Evolution API
  postgres-evolution:
    image: postgres:15-alpine
    container_name: postgres-evolution
    restart: unless-stopped
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evolution
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-evolution123}
    volumes:
      - postgres_evolution_data:/var/lib/postgresql/data
    networks:
      - evolution-network

  # Redis for Evolution API
  redis-evolution:
    image: redis:7-alpine
    container_name: redis-evolution
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_evolution_data:/data
    networks:
      - evolution-network

volumes:
  evolution_instances:
  evolution_store:
  postgres_evolution_data:
  redis_evolution_data:

networks:
  evolution-network:
    driver: bridge