version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.0.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_TYPE: http
      SERVER_PORT: 8080
      SERVER_URL: https://evolution2.cloude.es
      
      DATABASE_ENABLED: true
      DATABASE_CONNECTION_URI: postgresql://evolution:evolution123@postgres-evolution:5432/evolution
      
      REDIS_ENABLED: true
      REDIS_URI: redis://redis-evolution:6379/0
      
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: evolution-api-key-2025
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: true
      
      WEBHOOK_GLOBAL_URL: ${N8N_WEBHOOK_URL:-https://n8n.cloude.es/webhook/evolution}
      WEBHOOK_GLOBAL_ENABLED: true
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: true
      
      QRCODE_LIMIT: 10
      QRCODE_COLOR: "#000000"
      
      CONFIG_SESSION_PHONE_CLIENT: WhatsApp Business
      CONFIG_SESSION_PHONE_NAME: SMS_SCANNER_APP
      
      LOG_LEVEL: info
      LOG_COLOR: true
    
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    
    depends_on:
      - postgres-evolution
      - redis-evolution

  postgres-evolution:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution123
    volumes:
      - postgres_evolution_data:/var/lib/postgresql/data

  redis-evolution:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_evolution_data:/data

volumes:
  evolution_instances:
  evolution_store:
  postgres_evolution_data:
  redis_evolution_data: